# -*- coding: utf-8 -*-
"""DataSetPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1326RWKwabiG7Wp6M5aLYsJ04DfNOpK1Z
"""

# Define two sets
E = {0, 2, 4, 6, 8}
N = {1, 2, 3, 5, 8}

# Perform set operations
union_result = E.union(N)
intersection_result = E.intersection(N)
difference_result = E.difference(N)
symmetric_difference_result = E.symmetric_difference(N)

# Display the results
print(f"Union of E and N is {union_result}")
print(f"Intersection of E and N is {intersection_result}")
print(f"Difference of E and N is {difference_result}")
print(f"Symmetric difference of E and N is {symmetric_difference_result}")

