# -*- coding: utf-8 -*-
"""PythonJan24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gwpwpCWVBn_QHsXRnuVDaBJ2Kj_omzH4
"""



print("Hello World!")